import { Geist_Mono, Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/Navbar";
import PageFooter from "./Components/Footer";

const roboto = Roboto({
  variable: "--font-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${roboto.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col font-sans bg-white">
        <Navbar />
        {children}
        <PageFooter/>
        </body>
    </html>
  );
}
